version: 1.0
services:
  web:
    runtime: python3
    build:
      dockerfile: Dockerfile
    port: 8080
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - S3_BUCKET_NAME=$S3_BUCKET_NAME
      - DOCUMENTDB_ENDPOINT=$DOCUMENTDB_ENDPOINT
      - DOCUMENTDB_PORT=$DOCUMENTDB_PORT
      - DOCUMENTDB_USERNAME=$DOCUMENTDB_USERNAME
      - DOCUMENTDB_PASSWORD=$DOCUMENTDB_PASSWORD
    command: python upload_and_record_metadata.py
